builds:
  - main: ./cmd/server
    binary: server
    id: "server"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/zryfish/kunnel/pkg/version.BuildVersion={{.Version}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

  - main: ./cmd/kn
    binary: kn
    id: "kn"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/zryfish/kunnel/pkg/version.BuildVersion={{.Version}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
