builds:
  - main: ./cmd/client
    binary: client
    id: "client"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/zryfish/kunnel/pkg/version.BuildVersion={{.Version}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

  - main: ./cmd/server
    binary: server
    id: "server"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/zryfish/kunnel/pkg/version.BuildVersion={{.Version}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

  - main: ./cmd/kn
    binary: kubectl-kn
    id: "kubectl-kn"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/zryfish/kunnel/pkg/version.BuildVersion={{.Version}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

archives:
  - format: gz
    files:
      - none*
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"